### ISSUE TITLE
Does this template still work?

### ISSUE THREAD

**Issue by rasikhq** [GameDrivenDesign/godot-multiplayer-template#15]
Hey, I'm new to Godot and I was looking for some networking plugins and I came about this template, I tried setting it up according to the steps in README but was having a few errors, I would like to know if this is still active and works with latest stable Godot thanks

**Comment by tom95** [comment]
Hi @DizzasTeR ! The plugin should generally work. Could you report what errors you encountered?

**Comment by rasikhq** [comment]
Basically I get this when I setup a project from scratch with my own nodes or if I take example3 project and set that up

![image](https://user-images.githubusercontent.com/16344370/161387317-32f40186-5a48-457c-ae01-b53521f9b725.png)

Edit: I just realized there's a breakpoint at that line, it is probably in the template because I don't recall adding a breakpoint in template code scripts or maybe I accidentally added it because I didn't set it up the first time correctly, whatever the case, it seems to be fixed

Thanks for your help!

**Comment by tom95** [comment]
Glad to hear that, thanks for following up! :)
