### ISSUE TITLE
Syncing Spatial Camera

### ISSUE THREAD

**Issue by rasikhq** [GameDrivenDesign/godot-multiplayer-template#16]
How can I properly sync Spatial Camera which is a child of a kinematic body?

This is what my Player.tscn looks like:
![image](https://user-images.githubusercontent.com/16344370/161546577-c32f8846-31f7-4c89-93f5-f7dbc55bed3e.png)

The issue:
![camera-issue](https://user-images.githubusercontent.com/16344370/161549041-fd3fcbe5-b102-42ce-aae4-a2bee9283932.gif)

I tried doing a few things like adding "camera" into the unrealiable-sync field (cuz I reference it in my player controller script), also tried adjusting node hierarchy for player to make it work somehow but I ended up with a bunch of errors if I move the Sync anywhere else in the Players.tscn

**Comment by tom95** [comment]
Hi! It was a bit difficult to see what the issue was in the recording. As a general rule: you can only have one client control one node. So both clients affecting a single camera will not work. If you add a `Sync` as a child of the KinematicBody and add `transform` to its synced list then both cubes should move when directed.

**Comment by rasikhq** [comment]
Hey thanks for the very quick response, much appreciated!

Yes they both in-fact do move which is the desired behavior, however whats not the desired behavior is that the Camera is the same for both clients, both instances Camera is following the same cube which is incorrect, I'm not sure how to fix that

I do have transform and rotation in sync list

**Comment by tom95** [comment]
Ah got it. In that case, try putting
```gdscript
func _process(delta):
    $Camera.current = is_network_master()
```
in your Player.gd, to ensure that the global camera is the one of the current client's. This should hopefully work in any case. If it works, you can consider placing it instead in _ready or _network_ready so that it's only run once.

**Comment by rasikhq** [comment]
Ah yes! I completely forgot to take the authority into consideration!

I fixed the rotation of the cube as well by checking for network master, and it also fixed the camera issue once I added your suggestion in _ready()

Thank you so much, hopefully I'll be able to finally make a networked game after all these years 😂
