### ISSUE TITLE
Allow choosing server vs. game mode via code

### ISSUE THREAD

**Issue by phkeese** [GameDrivenDesign/godot-multiplayer-template#6]
Starting the entire application with a command line flag to distinguish between server and client is tedious and locks in that instance of the application to the chosen mode. 

Instead, it should be possible to choose the mode via code. Perhaps a Singleton would do the trick, something like `Multiplayer.start_server(port: int, player_count: int)` and `Multiplayer.join_server(port: int, ip: String)` for hosting and joining,

I am not sure how I would go about implementing this, but maybe `get_tree().change_scene_to()` would be helpful.

**Comment by tom95** [comment]
Hey! Is your usecase building a lobby or similar? Or is it actually about changing server/client mid-game or between matches?

**Comment by phkeese** [comment]
I just want to be able to choose the mode without command line arguments, Changing mode between matches would be nice but not necessary.

**Comment by tom95** [comment]
Okay, the entire structure of the project just got a major update. It's now a proper plugin with a built-in function for starting multiple clients, refer to the README for more details :)

In the process I also made it possible to toggle auto-connecting: https://github.com/GameDrivenDesign/godot-multiplayer-template/commit/753be23c029874ed9ce39649808f4e6294f57ef8

Could you take a look and reopen the issue if this is not sufficient for your use case? :)

What could be considered is adding some support for connecting to specific ports/hosts with a pre-built UI element that people can simply drop in. I'd tend to track this in a separate issue though to discuss the design.
